data <- read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F,sep=';',stringsAsFactors=FALSE,na.strings="?")
colnames(data) <- names(read.table("household_power_consumption.txt",header=TRUE,sep=';',nrows=1))
dates <- strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
png(file="plot4.png",width=480,height=480)
par(mfcol=c(2,2))

plot(dates,data$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(dates,data$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
lines(dates,data$Sub_metering_1,col="black")
lines(dates,data$Sub_metering_2,col="red")
lines(dates,data$Sub_metering_3,col="blue")
legend("topright", col = c("black", "red", "blue"), lty= "solid", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),bty="n" )
plot(dates,data$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(dates,data$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()